"""
CRITICAL FIXES FOR BATTLE UI
Generated by Forensic Analysis - MUST BE APPLIED IMMEDIATELY
"""

# FIX 1: Add missing connect_event_handlers method to BattleUI
def connect_event_handlers(self, event_processor):
    """Connect UI to event processor - CRITICAL CONNECTION."""
    if not event_processor:
        return
    
    self.event_processor = event_processor
    
    # Register handlers for all event types
    from engine.systems.battle.event_processor import EventType
    
    # Message events
    event_processor.register_handler(EventType.MESSAGE_SHOW, self._handle_message_event)
    
    # HP updates
    event_processor.register_handler(EventType.HP_BAR_UPDATE, self._handle_hp_update_event)
    event_processor.register_handler(EventType.DAMAGE_DEALT, self._handle_damage_event)
    event_processor.register_handler(EventType.HEALING_DONE, self._handle_healing_event)
    
    # Status changes
    event_processor.register_handler(EventType.STATUS_APPLIED, self._handle_status_event)
    event_processor.register_handler(EventType.STATUS_REMOVED, self._handle_status_event)
    
    # Monster events
    event_processor.register_handler(EventType.MONSTER_FAINTED, self._handle_faint_event)
    event_processor.register_handler(EventType.MONSTER_SWITCH, self._handle_switch_event)
    
    # Phase changes
    event_processor.register_handler(EventType.PHASE_CHANGE, self._handle_phase_change_event)
    
    print(f"[UI] Connected {len(event_processor.event_handlers)} event handlers")

# FIX 2: Add missing __init__ attributes
def fix_init(self, game):
    """Add to existing __init__ - CRITICAL ATTRIBUTES."""
    # ... existing init code ...
    
    # CRITICAL: Initialize pending action
    self._pending_action = None
    
    # CRITICAL: Initialize battle state reference
    self.battle_state = None
    
    # Initialize message queue if not exists
    if not hasattr(self, 'message_queue'):
        self.message_queue = []
    
    # Initialize event processor reference
    self.event_processor = None

# FIX 3: Add get_action_result method
def get_action_result(self):
    """Get and clear pending action - CRITICAL FOR ACTION FLOW."""
    if self._pending_action:
        action = self._pending_action
        self._pending_action = None
        return action
    return None

# FIX 4: Add apply_update method
def apply_update(self, update):
    """Apply UI update from event processor."""
    if not update or not hasattr(update, 'update_type'):
        return
    
    update_type = update.update_type
    data = update.data if hasattr(update, 'data') else {}
    
    if update_type == 'message':
        self.add_message(data.get('message', ''))
    elif update_type == 'hp_bar':
        target = data.get('target')
        if target:
            self.update_hp_bar(target)
    elif update_type == 'damage':
        self._show_damage_number(data)
    elif update_type == 'status_change':
        self._update_status_display(data)
    elif update_type == 'phase_change':
        self._handle_phase_change(data)

# FIX 5: Add reset_to_main_menu method
def reset_to_main_menu(self):
    """Reset UI to main battle menu."""
    self.menu_state = BattleMenuState.MAIN
    self.cursor_pos = 0
    self.cursor_row = 0
    self.cursor_col = 0
    self.selected_move_id = None
    self.selected_item_id = None
    self.selected_target = None

# FIX 6: Unify message methods
def add_message(self, message):
    """Add message to queue - UNIFIED METHOD."""
    if message:
        self.message_queue.append(message)
        self.current_message = message
        self.message_timer = 60  # frames
        self.message_char_index = 0

def show_message(self, message):
    """Alias for add_message for compatibility."""
    self.add_message(message)

# FIX 7: Add missing event handler methods
def _handle_message_event(self, event):
    """Handle message display events."""
    if hasattr(event, 'data'):
        message = event.data.get('message', '')
        if message:
            self.add_message(message)

def _handle_hp_update_event(self, event):
    """Handle HP bar update events."""
    if hasattr(event, 'data'):
        target = event.data.get('target')
        if target:
            # Trigger HP animation
            self.update_hp_bar(target)

def _handle_damage_event(self, event):
    """Handle damage display events."""
    if hasattr(event, 'data'):
        damage = event.data.get('damage', 0)
        target = event.data.get('target')
        if damage and target:
            # Show damage number
            pos = self._get_monster_position(target)
            self.damage_numbers.append(DamageNumber(
                value=damage,
                position=pos,
                timer=0,
                velocity=(0, -1),
                color=(255, 255, 255)
            ))

def _handle_healing_event(self, event):
    """Handle healing display events."""
    if hasattr(event, 'data'):
        healing = event.data.get('healing', 0)
        target = event.data.get('target')
        if healing and target:
            # Show healing number
            pos = self._get_monster_position(target)
            self.damage_numbers.append(DamageNumber(
                value=healing,
                position=pos,
                timer=0,
                velocity=(0, -1),
                color=(100, 255, 100)
            ))

def _handle_status_event(self, event):
    """Handle status change events."""
    if hasattr(event, 'data'):
        status = event.data.get('status')
        target = event.data.get('target')
        if status and target:
            # Update status display
            self._update_status_display({'target': target, 'status': status})

def _handle_faint_event(self, event):
    """Handle monster faint events."""
    if hasattr(event, 'data'):
        monster = event.data.get('monster')
        if monster:
            self.add_message(f"{monster.name} wurde besiegt!")

def _handle_switch_event(self, event):
    """Handle monster switch events."""
    if hasattr(event, 'data'):
        switch_to = event.data.get('switch_to')
        if switch_to:
            self.add_message(f"{switch_to.name} kommt ins Spiel!")

def _handle_phase_change_event(self, event):
    """Handle battle phase changes."""
    if hasattr(event, 'data'):
        phase = event.data.get('phase')
        # Update UI state based on phase
        pass

# FIX 8: Add update_hp_bar method if missing
def update_hp_bar(self, target):
    """Update HP bar animation for target."""
    if not target:
        return
    
    # Create HP animation entry
    target_id = str(id(target))
    if target_id not in self.hp_animations:
        self.hp_animations[target_id] = {
            'current': target.current_hp,
            'target': target.current_hp,
            'max': target.max_hp,
            'timer': 0
        }
    else:
        self.hp_animations[target_id]['target'] = target.current_hp

# FIX 9: Helper methods
def _get_monster_position(self, monster):
    """Get screen position of monster for effects."""
    # Check if monster is player or enemy
    if self.battle_state:
        if monster == self.battle_state.player_active:
            return (240, 90)  # Player side
        elif monster == self.battle_state.enemy_active:
            return (80, 30)  # Enemy side
    return (160, 60)  # Default center

def _update_status_display(self, data):
    """Update status condition display."""
    # Update visual status indicators
    pass

def _handle_phase_change(self, data):
    """Handle battle phase changes."""
    # Update menu state based on phase
    pass

# FIX 10: Add init_battle method if missing
def init_battle(self, player_team, enemy_team):
    """Initialize battle UI with teams."""
    self.player_team = player_team
    self.enemy_team = enemy_team
    self.reset_to_main_menu()
    
    # Clear any previous state
    self.message_queue.clear()
    self.damage_numbers.clear()
    self._pending_action = None

"""
INTEGRATION INSTRUCTIONS:
1. Add ALL these methods to engine/ui/battle_ui.py (PixelBattleUI class)
2. Add missing attributes to __init__
3. Test with: python test_battle_quick.py
4. Monitor console for connection confirmations
"""
